### ISSUE TITLE
Support for conditional delete

### ISSUE THREAD

**Issue by m0rl** [beda-software/fhir-py#10]
It would be great if we could use conditional delete (as described [here](https://hl7.org/fhir/2018May/http.html#3.1.0.13.1)) to clean up linked resources.

**Comment by ruscoder** [comment]
@pavlushkin please close it if it's completed within #112

**Comment by pavlushkin** [comment]
Implemented: https://github.com/beda-software/fhir-py/pull/114/commits/ef172bf2e0217ac03a8002c5c0e5c7c9d19202cf
