### ISSUE TITLE
Getting _elements when using reference not supported

### ISSUE THREAD

**Issue by BSVogler** [beda-software/fhir-py#101]
I want to send this query.

`/Patient/83ed7f8c-8a80-47d6-bd70-3923baa5c076?_elements=address`

I tried this 

```python
client.reference('Patient', id=user_id).elements("address").to_resource()
```

but this throws an AttributeError that elements is not found.

This works instead but is building internally a different query
```python
client.resources('Patient').search(_id=user_id).elements("address").get()
```

**Comment by ruscoder** [comment]
I don't remember that [FHIR spec](https://www.hl7.org/fhir/search.html) describes `_elements` for the particular resource, it's more list operation.

**Comment by BSVogler** [comment]
True. It is supported on HAPI FHIR though.
