### ISSUE TITLE
Move common functional to base-fhir-py

### ISSUE THREAD

**Issue by ruscoder** [beda-software/fhir-py#11]
* Rename FHIRClient -> Client, FHIRResource -> Resource, FHIRBaseResource -> AbstractResource, FHIRReference -> Reference, FHIRSearchSet -> SearchSet
* Make them abstract
* In Client specify searchset_class, resource_class, reference_class and use them in public API (resource, resources, reference)
* Remove load_schema, validation, fhir_version, schema, root_keys make raise_error_if_invalid_keys public and empty by default
* Make Reference.resource_type, Reference.id, Reference.reference abstract
* Make AbstractResource.is_reference non static, abstract and move into Resource
* In SearchSet.clone use self.__class__ to instantiate a copy

**Comment by mkizesov** [comment]
Done https://github.com/beda-software/base-fhir-py

**Comment by mkizesov** [comment]
This logic will be moved to fhirpy.base.
base-fhir-py will be removed.
