### ISSUE TITLE
Setup fhir-py using base-fhir-py

### ISSUE THREAD

**Issue by ruscoder** [beda-software/fhir-py#12]
* Create classes FHIRClient, FHIRResource, FHIRReference, FHIRSearchSet based on classes from base-fhir-py
* Override FHIRReference.id, FHIRReference.resource_type, FHIRReference.reference
* Add validation using FHIRResource.raise_error_if_invalid_keys FHIRReference.raise_error_if_invalid_keys

**Comment by mkizesov** [comment]
We've implemented it here https://github.com/beda-software/fhir-py/tree/base
