### ISSUE TITLE
on 200 response JSON is not being properly decoded

### ISSUE THREAD

**Issue by woodsjs** [beda-software/fhir-py#18]
When making a get call on multiple end points, both open (http://hapi.fhir.org/baseDstu3) and EMR Vendor based (Epic 2018, Epic August 2018) receive error

> the JSON object must be str, not 'bytes'

This is caused by a missing .decode() call on r.content, here's the broken piece of code. Notice the 200 call is the only one without a .decode()

```
        if 200 <= r.status_code < 300:
            return json.loads(r.content) if r.content else None

        if r.status_code == 404:
            raise FHIRResourceNotFound(r.content.decode())

        raise FHIROperationOutcome(r.content.decode())
```

This simple example shows the issue

```
from fhirpy import FHIRClient

client = FHIRClient(url='http://hapi.fhir.org/baseDstu3')
resources = client.resources('Practitioner').get(id=1700173)
```

I have a fix in place I'm using currently and will submit a pull request.

**Comment by woodsjs** [comment]
Submitted pull request #19 to fix this issue

**Comment by ruscoder** [comment]
Hello @woodsjs! Thank you for your contribution! We'll review your pull requests soon.
