### ISSUE TITLE
No "extra headers" can be added to requests

### ISSUE THREAD

**Issue by woodsjs** [beda-software/fhir-py#20]
Several EHR vendors, including Epic, require headers that cannot be passed in, or make no sense to be passed in, with the current state of the object constructor. These are typically used for things like client IDs and additional authorization for access. 

I have a solution currently implemented and being used with a large EHR installation. I add an extra_headers attribute to the object, defaulted to None. When not None, the extra_headers attribute is unpacked into the headers variable.

If you can please assign this bug to me, I will submit a pull request for the solution within the next few days.

**Comment by mkizesov** [comment]
Done. @woodsjs thank you for contribution!
