### ISSUE TITLE
Add support for conditional CRUD

### ISSUE THREAD

**Issue by ruscoder** [beda-software/fhir-py#39]
TBD

**Comment by ruscoder** [comment]
Use ideas from https://github.com/beda-software/aidbox-react/issues

**Comment by ir4y** [comment]
API may be inspired by Django get_or_create https://docs.djangoproject.com/en/3.1/ref/models/querysets/#get-or-create

**Comment by ruscoder** [comment]
Related PR #112

**Comment by ruscoder** [comment]
https://miro.com/app/board/uXjVMvMgnFQ=/

**Comment by pavlushkin** [comment]
Implemented in:
- https://github.com/beda-software/fhir-py/pull/112
- https://github.com/beda-software/fhir-py/pull/114
