### ISSUE TITLE
search: Add support for chained search

### ISSUE THREAD

**Issue by ruscoder** [beda-software/fhir-py#43]
GET /EpisodeOfCare?patient:Patient.name=Ivan

**Comment by ruscoder** [comment]
It can be something like `.search(patient={Patient__name='Ivan'})` or something else. Any ideas?

**Comment by ir4y** [comment]
We can keep using Django way for chaining.
 ```
.search(patient__Patient__name = Ivan)
```
What do you think?

**Comment by ruscoder** [comment]
FHIR specification also supports `GET /EpisodeOfCare?patient.name=Ivan` without specifying the target resource. But Aidbox requires the target resource type to be specified.

I like Django way more than I suggested. Let's implement it with target resource type restriction.

Some examples:
```
client.resources('EpisodeOfCare').search(patient__Patient__birth_date__gt='2010')
client.resources('EpisodeOfCare').search(patient__Patient__name='Ivan')
```

**Comment by ruscoder** [comment]
There is only one disadvantage - too long kwarg name

**Comment by ruscoder** [comment]
Done in master branch
