### ISSUE TITLE
searchset.py not in 1.0.0?

### ISSUE THREAD

**Issue by kylejbrk** [beda-software/fhir-py#46]
The documentation mentions you can use Raw Parameters using the following:

```python
from fhirpy.base.searchset import Raw

patients = client.resources('Patient')
patients.search(Raw('general-practitioner.name=Hospital'))
# /Patient?general-practitioner.name=Hospital
```

However, after downloading the source code for 1.0.0 it appears that searchset.py was not included in the release. Is this a mistake?

**Comment by ruscoder** [comment]
Hello! The documentation is about the latest version 1.1.0.

**Comment by kylejbrk** [comment]
@ruscoder Ah thank you. Is this version not available on pip yet? I also didn't see it in the releases.

Thank you for pointing this out.

**Comment by mkizesov** [comment]
Hello @kylejbrk ,
fhirpy v. 1.1.0 is available in PyPi https://pypi.org/project/fhirpy/
You can try `pip install fhirpy==1.1.0` or `pip install fhirpy -U`

**Comment by kylejbrk** [comment]
Thank you both. Much appreciated.
