### ISSUE TITLE
fetch_all() Creating Infinite Loop.

### ISSUE THREAD

**Issue by kylejbrk** [beda-software/fhir-py#47]
Not sure if this problem is specific to the FHIR Server I am pulling from, but supplying a page number will always return a bundle with resources. The current fetch_all() code uses this:

```python
while True:
    new_resources = await self.page(page).fetch()
        if not new_resources:
            break
```

Since my server always returns something regardless of the page number, it gets stuck in the loop above. The way I've gotten around this in the past is to refer to the next [link in the Bundle ](https://www.hl7.org/fhir/bundle-definitions.html#Bundle.link ).

I suppose a quick and dirty solution would be something like the following:

```python
async def fetch(self):
    bundle_data = await self.client._fetch_resource(
        self.resource_type, self.params
    )
    bundle_resource_type = bundle_data.get('resourceType', None)

    ...
    
    next_link = None
    for link in bundle_data.get('link', []):
        if link['relation'] == 'next':
            next_link = link['url']
    
    return resources, next_link

async def fetch_all(self):
    page = 1
    resources = []

    while True:
        new_resources, next_link = await self.page(page).fetch()
        resources.extend(new_resources)
        
        if not next_link:
            break
            
        page += 1

    return resources
```

**Comment by mkizesov** [comment]
Sure, I think it's a bug. Thank you for pointing this out, @kylejbrk .
We'll fix it soon

**Comment by kylejbrk** [comment]
I tried digging for the page parameter in the docs, but I couldn't find it.
It doesn't look like my client supports it at all, hence why it's getting stuck in the loop.

So perhaps the page parameter is not part of the FHIR standard?

**Comment by mkizesov** [comment]
Yep, of course. As far as I know now, FHIR standard doesn't specify which parameters should be used for paging. Client just have to use a link provided in "next" relation from a response (if exists).

**Comment by mkizesov** [comment]
Done.
