### ISSUE TITLE
Is there a way to refresh a Token?

### ISSUE THREAD

**Issue by kylejbrk** [beda-software/fhir-py#63]
When using a bearer token, is there a way to refresh it when it expires? 
Or will I have to create a new client instance each time?

**Comment by ir4y** [comment]
Hi @kylejbrk 

Token lifecycle management is not a part of the library, so you have to implement it on your own.
You may create a new client instance once the token is expired or just update the `authorization` attribute of the client instance.  Both ways are ok.

**Comment by kylejbrk** [comment]
Curious, why isn't it within the scope of this library?
Isn't that part of the FHIR authentication standard?

**Comment by mkizesov** [comment]
Sorry for the late response, @kylejbrk .
As I know, it isn't a part of FHIR standart. `Fast Healthcare Interoperability Resources (FHIR) is not a security protocol, nor does it define any security related functionality.` https://www.hl7.org/fhir/security.html
