### ISSUE TITLE
Accessing invalid field returns key error and not attribute error

### ISSUE THREAD

**Issue by BSVogler** [beda-software/fhir-py#66]
When you have an FHIR resource object and try to access a field, which does no exists you get a KeyError. Python standard is AttributeError.

This causes `hasattr(fhirresource, "field")` to return an error instead of `False`, because internally it catches an attribute error and not a key error.

**Comment by mkizesov** [comment]
Just to clarify. You prefer to access resource's fields as attributes like this `patient.gender`, do you?

**Comment by BSVogler** [comment]
It is supported by the library so I might use it.

**Comment by ir4y** [comment]
Close since PR with the fix was merged.
