### ISSUE TITLE
Pickling not supported

### ISSUE THREAD

**Issue by BSVogler** [beda-software/fhir-py#77]
When saving resources with pickle and then instantiating again you will get this message:

> KeyError: 'Can not change `resourceType` after instantiating resource. You must re-instantiate resource using `Client.resource` method

Dumping resources to a file and later loading them again should be supported. If pickle cannot be supported maybe providing another format translation e.g. to json can be used?

**Comment by ruscoder** [comment]
Fixed in 2.0.0
