### ISSUE TITLE
Example  re: paging through a FHIR bundle?

### ISSUE THREAD

**Issue by cbarina** [beda-software/fhir-py#84]
I want to summarize what codes are in a certain dataset (loinc codes), on DocumentReference.

I am trying to understand how one could iterate through a search result. I understand .limit(x) gives you the first x results, but then if you have a count >100, how do you go to the next page/set of results?

I have also tried fetch_all(), but there are about 1M records I am pulling so it isn't ideal.

**Comment by mkizesov** [comment]
You can iterate through search using lazy fetch with `async for` on searchset like this:
```python3
async for document_reference in client.resources('DocumentReference').limit(100):
        print(document_reference.id)
```

`limit()` is an example of a bad naming here :) it means page size
