### ISSUE TITLE
AsyncFHIRClient's aiohttp throwing SSLCertVerificationError

### ISSUE THREAD

**Issue by balint729** [beda-software/fhir-py#85]
Hi All!

We're having issues with AsyncFHIRClient's aiohttp throwing SSLCertVerificationError tried several ways of setting up the SSL Certificate context but as AsyncClient calls aiohttp like:
 `async with aiohttp.request(method, url, json=data, headers=headers) as r:`
We don't have any influence on passing the SSL Context to aiohttp.

It does not help to set the usual env. variables used for this either

Could you please advise how this could be solved?

Thank you in advance.
BR,
Bálint

**Comment by mkizesov** [comment]
Link in the docs [aiohttp-request-parameters](https://github.com/beda-software/fhir-py#aiohttp-request-parameters)

**Comment by balint729** [comment]
Great news, thanks for the quick response! 👍

**Comment by ir4y** [comment]
The fix is merged
